In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import preprocessing

### Read Data

In [2]:
df = pd.read_csv(r"D:\3.6120 DATA SCIENCE II\IBM-Attrition.csv")

In [6]:
df

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

### Process Data

In [7]:
le = preprocessing.LabelEncoder()

In [8]:
df_encoded = df.apply(le.fit_transform)

In [9]:
df_encoded

Age  Attrition  BusinessTravel  DailyRate  Department  DistanceFromHome  \
0      23          1               2        624           2                 0   
1      31          0               1        113           1                 7   
2      19          1               2        805           1                 1   
3      15          0               1        820           1                 2   
4       9          0               2        312           1                 1   
...   ...        ...             ...        ...         ...               ...   
1465   18          0               1        494           1                22   
1466   21          0               2        327           1                 5   
1467    9          0               2         39           1                 3   
1468   31          0               1        579           2                 1   
1469   16          0               2        336           1                 7   

      Education  EducationField  EmployeeCount  EmployeeNumber  ...  \
0             1               1              0               0  ...   
1             0               1              0               1  ...   
2             1               4              0               2  ...   
3             3               1              0               3  ...   
4             0               3              0               4  ...   
...         ...             ...            ...             ...  ...   
1465          1               3              0            1465  ...   
1466          0               3              0            1466  ...   
1467          2               1              0            1467  ...   
1468          2               3              0            1468  ...   
1469          2               3              0            1469  ...   

      RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                            0              0                 0   
1                            3              0                 1   
2                            1              0                 0   
3                            2              0                 0   
4                            3              0                 1   
...                        ...            ...               ...   
1465                         2              0                 1   
1466                         0              0                 1   
1467                         1              0                 1   
1468                         3              0                 0   
1469                         0              0                 0   

      TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                     8                      0                0   
1                    10                      3                2   
2                     7                      3                2   
3                     8                      3                2   
4                     6                      3                2   
...                 ...                    ...              ...   
1465                 17                      3                2   
1466                  9                      5                2   
1467                  6                      0                2   
1468                 17                      3                1   
1469                  6                      3                3   

      YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                  6                   4                        0   
1                 10                   7                        1   
2                  0                   0                        0   
3                  8                   7                        3   
4                  2                   2                        2   
...              ...                 ...                      ...   
1465               5                   2                        0   
1466              

### Prepare for Gradient Bossting

In [10]:
X_df = df_encoded.drop('Attrition', axis=1)
X = X_df.to_numpy()

In [11]:
Y = df_encoded['Attrition'].values

In [12]:
X.shape

(1470, 34)

In [14]:
np.random.seed(0)
idx = np.arange((X.shape[0]))
np.random.shuffle(idx)
idx

array([ 442, 1091,  981, ..., 1216,  559,  684])

In [15]:
# train numbers
num = int(X.shape[0] * 0.8)
num

1176

In [16]:
X_train, X_test = X[idx[:num]], X[idx[num:]]
Y_train, Y_test = Y[idx[:num]], Y[idx[num:]]

### GB

In [17]:
clf = GradientBoostingClassifier(max_depth=10, n_estimators=100, random_state=0).fit(X_train, Y_train)

In [18]:
clf

GradientBoostingClassifier(max_depth=10, random_state=0)

In [19]:
#ACC

clf.score(X_test, Y_test)

0.8367346938775511

In [20]:
# Predicted Attrition

clf.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0])

In [21]:
#Ground truth Attrition

Y_test

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0])

### Compute the importance for each feature

221

In [22]:
clf.feature_importances_

array([0.05794877, 0.00342995, 0.05117821, 0.00514682, 0.03651139,
       0.00946969, 0.00988628, 0.        , 0.04457892, 0.02613292,
       0.00404783, 0.08907377, 0.02786653, 0.00276719, 0.04212865,
       0.02960734, 0.03244559, 0.13511238, 0.0468177 , 0.03033957,
       0.        , 0.06803295, 0.02694583, 0.00055632, 0.0167422 ,
       0.        , 0.01182978, 0.0402886 , 0.02196019, 0.02642522,
       0.02711288, 0.02204252, 0.02798421, 0.02558983])

In [23]:
X_df.columns.values

array(['Age', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'], dtype=object)

In [24]:
importance_idx = np.argsort( - clf.feature_importances_)

In [25]:
# Order of importance

X_df.columns.values[importance_idx]

array(['MonthlyIncome', 'HourlyRate', 'OverTime', 'Age', 'DailyRate',
       'MonthlyRate', 'EmployeeNumber', 'JobRole', 'TotalWorkingYears',
       'DistanceFromHome', 'MaritalStatus', 'NumCompaniesWorked',
       'JobSatisfaction', 'YearsSinceLastPromotion', 'JobInvolvement',
       'YearsAtCompany', 'PercentSalaryHike', 'WorkLifeBalance',
       'EnvironmentSatisfaction', 'YearsWithCurrManager',
       'YearsInCurrentRole', 'TrainingTimesLastYear',
       'RelationshipSatisfaction', 'StockOptionLevel', 'EducationField',
       'Education', 'Department', 'Gender', 'BusinessTravel', 'JobLevel',
       'PerformanceRating', 'Over18', 'StandardHours', 'EmployeeCount'],
      dtype=object)

### Random Forest

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
clf2 = RandomForestClassifier(max_depth=5, n_estimators=10, random_state=0).fit(X_train, Y_train)

In [28]:
clf2.score(X_test, Y_test)

0.8299319727891157

### SVM

In [29]:
from sklearn.svm import SVC

In [30]:
clf3 = SVC()

In [31]:
clf3.fit(X_train, Y_train)

SVC()

In [32]:
clf3.score(X_test, Y_test)

0.8197278911564626

In [ ]:
1111